[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bamsalvage"
version = "0.0.1"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "Sequence salvaging script from corrupted BAM files"
readme = "README.md"
licence = "MIT"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["numpy>=1.17", "numba>=0.4"]

[project.urls]
Homepage = "https://github.com/takaho/bamsalvage"

[tool.hatch.version]
scheme = "standard"

[tool.hatchling]
entry-point="bamsalvate:main"

[tool.hatchling.scripts]
bamsalvage = "bamsalvage:main"